# Site settings
title: Rob van Bekkum
description: 'Student MSc Computer Science at Delft University of Technology'
url: 'http://robvanbekkum.nl'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Rob van Bekkum'
  #email: <private>
  #twitter_username: -
  #facebook_username: <private>
  github_username:  rvanbekkum
  linkedin_username:  robvanbekkum

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
timezone: Europe/Amsterdam
